### ISSUE TITLE
Unauthorized use of my GitHub Code

### ISSUE THREAD

**Issue by Sbrjt** [iamaako/character-certificate#2]
It has come to my attention that you used code from my GitHub repo [josaa-cutoffs](https://github.com/Sbrjt/josaa-cutoffs) without my permission on your [website](https://jee-college-predictor.netlify.app/jeemains/).

Personally, I don't mind you using my code, but I must insist that you must provide proper attribution/credit to me on your website with a link to my github repo.

Failure to do so will leave me with no choice but to report this copyright infringement to Netlify support and request the takedown of your website.

**Comment by iamaako** [comment]
Bhai maine tumhe contact karne ki kosis kari thiii mai tumhare saath kaam
krna chata hu kyu nah abhi bhi sathme kiya jaaye & isse aur achi website
bnai jaaye.... My telegram @i_am_aarif yah message karna bhai... Tumhara
thoda data & logic humne change kiyaaa hai but koi dikkat nhi bhai Credit
de denge aram se baat karte hai message kar dena mujhe telegram par

**Comment by Sbrjt** [comment]
Just gimme a credit line in the footer. Something like:

> Forked from [josaa-cutoffs](https://github.com/Sbrjt/josaa-cutoffs) by [Sbrjt](https://github.com/Sbrjt)

And I'll have no issue :)

**Comment by Sbrjt** [comment]
Good job! 👍
